const crypto = require('crypto');

const MOCK_SECRET = process.env.MOCK_PAYMENT_SECRET || 'dev_only_mock_secret';

/**
 * Mimics Razorpay's orders.create() — returns a fake order to attach to a booking.
 */
function createOrder({ amount, currency, receipt }) {
  const id = `order_mock_${crypto.randomBytes(8).toString('hex')}`;
  return {
    id,
    amount,
    currency,
    receipt,
    status: 'created',
  };
}

/**
 * Stands in for the real Razorpay checkout popup. In the real flow, this
 * signature would be generated by Razorpay's servers after a real payment;
 * here we generate it ourselves so the rest of the flow (verification)
 * behaves identically to production.
 */
function simulatePayment(orderId) {
  const paymentId = `pay_mock_${crypto.randomBytes(8).toString('hex')}`;
  const signature = crypto
    .createHmac('sha256', MOCK_SECRET)
    .update(`${orderId}|${paymentId}`)
    .digest('hex');

  return { paymentId, signature };
}

/**
 * Same shape as Razorpay's real signature check: recompute the HMAC from
 * orderId + paymentId, compare against what was provided.
 */
function verifySignature({ orderId, paymentId, signature }) {
  const expectedSignature = crypto
    .createHmac('sha256', MOCK_SECRET)
    .update(`${orderId}|${paymentId}`)
    .digest('hex');

  return expectedSignature === signature;
}

module.exports = { createOrder, simulatePayment, verifySignature };